services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      PROJECT_ENVIRONMENT: development
      NEXT_PUBLIC_PROJECT_ENVIRONMENT: development
      API_BASE_URL: http://backend:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src
          ignore:
            - node_modules/
            - .next/

        - action: rebuild
          path: ./frontend/package.json

        - action: rebuild
          path: ./frontend/package-lock.json

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      PROJECT_ENVIRONMENT: development
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://user:password@db:5432/app_db
    depends_on:
      - db

    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./backend/pyproject.toml

        - action: rebuild
          path: ./backend/uv.lock

  db:
    image: postgres:18.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql

volumes:
  app_db_data: